SELECT	BLR.[KEEPER_ID] AS KeepID, 
		MM.[USER_CNAME] AS CName ,
		MM.[USER_ENAME] AS EName ,
		FORMAT(LEND_DATE,'yyyy') AS BorrowYear ,
		COUNT(BLR.[KEEPER_ID]) AS BorrowCnt
FROM BOOK_LEND_RECORD AS BLR
INNER JOIN MEMBER_M AS MM
ON BLR.[KEEPER_ID] = MM.[user_id]

GROUP BY BLR.[KEEPER_ID] , MM.[USER_CNAME] , MM.[USER_ENAME] , FORMAT(LEND_DATE,'yyyy')
ORDER BY KEEPER_ID
