SELECT	A.ClassID,
		A.ClassName,
		MAX(CASE A.[year] 
			WHEN 2016 THEN A.Cnt ELSE 0 END )AS 'CNT2016',
		MAX(CASE A.[year] 
			WHEN 2017 THEN A.Cnt ELSE 0 END )AS 'CNT2017',
		MAX(CASE A.[year] 
			WHEN 2018 THEN A.Cnt ELSE 0 END )AS 'CNT2018',
		MAX(CASE A.[year] 
			WHEN 2019 THEN A.Cnt ELSE 0 END )AS 'CNT2019'

FROM(
	SELECT	bc.BOOK_CLASS_ID AS ClassID,
			bc.BOOK_CLASS_NAME AS ClassName,
			YEAR(FORMAT(blr.LEND_DATE,'yyyy')) AS [year],
			COUNT(FORMAT(blr.LEND_DATE,'yyyy')) AS Cnt

	FROM BOOK_DATA AS bd
	INNER JOIN BOOK_CLASS AS bc
	ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
	INNER JOIN BOOK_LEND_RECORD AS blr
	ON blr.BOOK_ID = bd.BOOK_ID
	GROUP BY bc.BOOK_CLASS_NAME,bc.BOOK_CLASS_ID , FORMAT(blr.LEND_DATE,'yyyy') 
) A


GROUP BY A.ClassID , A.ClassName 
ORDER BY A.ClassID