SELECT	pvt.ClassID,
		pvt.ClassName,
		CASE 
			WHEN pvt.[2016] IS NULL THEN '0' ELSE pvt.[2016] END AS 'CNT2016',
		CASE 
			WHEN pvt.[2017] IS NULL THEN '0' ELSE pvt.[2017] END AS 'CNT2017',
		CASE 
			WHEN pvt.[2018] IS NULL THEN '0' ELSE pvt.[2018] END AS 'CNT2018',
		CASE 
			WHEN pvt.[2019] IS NULL THEN '0' ELSE pvt.[2019] END AS 'CNT2019'

FROM(
	SELECT	bc.BOOK_CLASS_ID AS ClassID,
			bc.BOOK_CLASS_NAME AS ClassName,
			YEAR(FORMAT(blr.LEND_DATE,'yyyy')) AS [year],
			COUNT(FORMAT(blr.LEND_DATE,'yyyy')) AS Cnt

	FROM BOOK_DATA AS bd
	INNER JOIN BOOK_CLASS AS bc
	ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
	INNER JOIN BOOK_LEND_RECORD AS blr
	ON blr.BOOK_ID = bd.BOOK_ID
	
	GROUP BY bc.BOOK_CLASS_NAME,bc.BOOK_CLASS_ID , FORMAT(blr.LEND_DATE,'yyyy') 
) A
PIVOT(
	SUM(A.Cnt)
	FOR A.[year] IN ([2016],[2017],[2018],[2019])
)AS pvt
ORDER BY pvt.ClassID